<a href="https://colab.research.google.com/github/baberraheem055/Machine-Learning-Repo/blob/main/K_Fold_Cross_Validation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#summary

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# Load the Iris dataset
data = sns.load_dataset('iris')
print(data.head())  # Display the first few rows of the dataset

# Replace 'setosa' with NaN to remove it for binary classification
data['species'] = data['species'].replace('setosa', pd.NA)

# Drop the rows with NaN values (i.e., the rows where 'species' is 'setosa')
filter_data = data.dropna(subset=['species'])

# Map the remaining 'species' to binary labels
species_mapping = {
    'versicolor': 0,
    'virginica': 1
}
filter_data['species'] = filter_data['species'].map(species_mapping)

# Split the data into features (X) and target (y)
X = filter_data.drop('species', axis=1)
y = filter_data['species']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Standardize the feature variables
#note :when training models, "convergence" refers to the process by which a model's training process gradually stabilizes and reaches a point where further learning (or optimization) no longer produces significant improvements in performance.

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


<ipython-input-3-0cfcf293dc1a>:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_data['species'] = filter_data['species'].map(species_mapping)


In [4]:
#Now We Have

# Now we have
- X_train
- X_test
- y_train
- y_test

In [5]:

# Train the logistic regression model
classifier = LogisticRegression(max_iter=200)
classifier.fit(X_train, y_train)

# Evaluate the model
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=['versicolor', 'virginica'])

print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(report)

Accuracy: 0.88
Classification Report:
              precision    recall  f1-score   support

  versicolor       0.92      0.86      0.89        14
   virginica       0.83      0.91      0.87        11

    accuracy                           0.88        25
   macro avg       0.88      0.88      0.88        25
weighted avg       0.88      0.88      0.88        25



# lets find the accuracy on other models
-

In [6]:
#svm
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.88

In [7]:
#randomforest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.84

# K fold Cross_validation

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# K fold Cross_validation for model selection


In [9]:
from sklearn.model_selection import cross_val_score
lr_score = cross_val_score(LogisticRegression(max_iter=200),X,y,cv=3)
lr_score_mean = lr_score.mean()

In [10]:
from sklearn.model_selection import cross_val_score
rf_score = cross_val_score(RandomForestClassifier(n_estimators= 40),X,y,cv=3)
rf_score_mean = rf_score.mean()

In [11]:
from sklearn.model_selection import cross_val_score
svm_score = cross_val_score(SVC(),X,y,cv=3)
svm_score_mean = svm_score.mean()

In [12]:
print("Mean Accuracy for Logistic Regression:", lr_score_mean)
print("Mean Accuracy for SVC:", svm_score_mean)
print("Mean Accuracy for Random Forest:", rf_score_mean)

# Compare and choose the best model
if (lr_score_mean > svm_score_mean) and (lr_score_mean > rf_score_mean):
    print("Logistic Regression is the better model.")
elif (svm_score_mean > lr_score_mean) and (svm_score_mean > rf_score_mean):
    print("SVC is the better model.")
else:
    print("Random Forest is the better model.")



Mean Accuracy for Logistic Regression: 0.9497920380273323
Mean Accuracy for SVC: 0.929590017825312
Mean Accuracy for Random Forest: 0.9497920380273323
Random Forest is the better model.
